application:
  port: 8000
  hmac_secret: "long-and-a-very-secret-key-which-no-one-will-know-the-key-was-too-short-so-lets-make-it-longer"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "this-is-my-real-token-obviously"
  timeout_milliseconds: 10000
