name: Zero2Prod Build & Test

on:
  push:
    branches:
      - main
      - 'feature-**'

env:
  CARGO_TERM_COLOR: always

jobs:

  test_phase:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v3

      # Github Actions installs Rust Toolchain using rustup
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@stable

      # Use smart caching for rust/cargo projects with sensible defaults
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable 
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchains@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --workspace


